name: DB Migrate (test)

on:
  push:
    branches: [ main ]

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      FLYWAY_URL: ${{ secrets.FLYWAY_URL }}
      FLYWAY_USER: ${{ secrets.FLYWAY_USER }}
      FLYWAY_PASSWORD: ${{ secrets.FLYWAY_PASSWORD }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Flyway
        run: |
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.15.2/flyway-commandline-10.15.2-linux-x64.tar.gz -o flyway.tar.gz
          tar -xzf flyway.tar.gz
          sudo mv flyway-10.15.2 /usr/local/flyway
          sudo ln -s /usr/local/flyway/flyway /usr/local/bin/flyway

      - name: Migrate schema on test DB
        run: flyway -configFiles=db/flyway.conf migrate
